apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-serv-ingress
  namespace: car-serv
spec:
  ingressClassName: nginx
  rules:
    - host: car-serv-onpre.phamnam.io # you can add host or write load balancer IP address
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: car-serv-clusterip-serv # cluster ip service basement from deployment
                port:
                  number: 80
