# In this Service, you don't have any choice to access to container, if you want, you must have api to access
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  namespace: namespace
  labels:
    app: cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: <application>-deployment
    ports:
      - protocol: TCP
        port: 80 # port in cluster
        targetPort: 80 # port in container port in deployment
